HTML/login/log.html

로그인 페이지 의사 코드 추가

---

HTML/main/main.css
HTML/main/main.html

html main page 연습

---

HTML/Terms/Term.css
HTML/Terms/Term.js

각각의 체크버튼을 전부다 클릭했을때 전체 동의 체크버튼이 활성화 되지 않는 것을 수정
어떤 변경 사항이 있나요?

체크 박스 논리구조 일부 수정

---

HTML/Terms/Term.css
HTML/Terms/TermFinal.html
HTML/login/log.html
HTML/registerReq/registerReq.css
HTML/registerReq/registerReq.html
HTML/registerReq/registerReq.js

회원 정보 입력 페이지 80% 완성
아직 완성하지 못한부분
1. 모든 정보 입력 완료시 버튼 활성화
2. 성별 선택 버튼 위치조정
3. 성별 선택 관련 경고 메시wl
4. 이메일 작성시 완벽하지 않으면 폰트가 겹치는 현상 
5. 핸드폰 번호도 마찬가지로 폰트가 겹치는 현상
6. datepicker 적용하기
#27 
어떤 변경 사항이 있나요?

RegisterReq 80% 와성

---

HTML/registerReq/registerReq.css
HTML/registerReq/registerReq.html

아이디 중복 확인버튼 위치 설정
#27 
어떤 변경 사항이 있나요?

regist request update

---

HTML/Terms/TermFinal.html
HTML/registerReq/assets/css/bootstrap-datepicker.css
HTML/registerReq/assets/css/bootstrap.css
HTML/registerReq/assets/css/date.css
HTML/registerReq/assets/js/bootstrap-datepicker.js
HTML/registerReq/assets/js/bootstrap.js
HTML/registerReq/assets/js/date.js
HTML/registerReq/assets/js/jquery-1.10.2.js
HTML/registerReq/registerReq.css
HTML/registerReq/registerReq.html
HTML/registerReq/registerReq.js

버튼 활성화 이전 디자인적인 요소 끝
어떤 변경 사항이 있나요?

버튼활성화 제외 모두 완성

---

HTML/registerReq/registerReq.css
HTML/registerReq/registerReq.html
HTML/registerReq/registerReq.js

버튼 활성화 제외 css 완성

---

HTML/Terms/TermFinal.html
HTML/login/log.html
HTML/registerReq/registerReq.css
HTML/registerReq/registerReq.html
HTML/registerReq/registerReq.js

회원 가입 버튼 활성도 완성했습니다
어떤 변경 사항이 있나요?

register Req 생일 입력 제외 끝

---

HTML/takeCode/takeCode.css
HTML/takeCode/takeCode.html
HTML/takeCode/takeCode.js
project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/AuthController.java
project/PSMC/src/main/java/com/javaclass/psmc/configuration/ContextConfiguration.java
project/PSMC/src/main/java/com/javaclass/psmc/user/controller/RegisterController.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/static/assets/css/takeCode.css
project/PSMC/src/main/resources/static/assets/js/registerReq.js
project/PSMC/src/main/resources/static/assets/js/takeCode.js
project/PSMC/src/main/resources/templates/member/registerReq.html
project/PSMC/src/main/resources/templates/member/takeCode.html

로그인 기능을 끝냈습니다
#60 
어떤 변경 사항이 있나요?

login 모든 경우의 수 끝

---

project/PSMC/src/main/resources/templates/auth/login.html

css link 추가

---

project/PSMC/src/main/resources/static/assets/css/mainpage.css

메인페이지 + 네비바

---

project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/AuthController.java
project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/AssignProjectDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/CreateProjectDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/EmployeeDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/InjuryDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/MediChatDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/MediConnectDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/MediInfoDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/MedicalFieldDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/MemberRegistDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/PatientDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/PositionDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/ProjectDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/ResTimeDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/TheraChatDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/TheraInfoDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/TheraLinkDTO.java
project/PSMC/src/main/resources/mappers/UserMapper.xml

전체 테이블 common DTO 생성

---

project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/ScheduleController.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/static/assets/js/schedule.js
project/PSMC/src/main/resources/templates/common/nav.html

schedule doc 부분 완료

---

project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/ScheduleController.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/AllMediDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/AllTheraDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/static/assets/js/schedule.js
project/PSMC/src/main/resources/templates/schedule/scheduler.html

scheduler 최종입니다
#62 
어떤 변경 사항이 있나요?

scheduler 완성

---

project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/ScheduleController.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/static/assets/css/schedule.css
project/PSMC/src/main/resources/static/assets/js/schedule.js
project/PSMC/src/main/resources/templates/schedule/scheduler.html

스케쥴러 하나 남음

---

HTML/mediConnect/mediConnect.css
HTML/mediConnect/mediConnect.html
HTML/mediConnectWrite/mediConnectWrite.css
HTML/mediConnectWrite/mediConnectWrite.html

mediConnect 게시판 html css

---

HTML/mediConnect/mediConnect.css
HTML/mediConnect/mediConnect.html
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/controller/MediConnectController.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/dao/ProjectsMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/dto/ShowMediConnectDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/service/MediConnectService.java
project/PSMC/src/main/resources/mappers/ProjectMapper.xml
project/PSMC/src/main/resources/templates/doc/mediConnect.html
project/PSMC/src/main/resources/templates/doc/projects.html

mediConnects 중간푸시

---

project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/controller/ProjectsController.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/dao/ProjectsMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/service/ProjectsService.java
project/PSMC/src/main/resources/mappers/ProjectMapper.xml
project/PSMC/src/main/resources/templates/doc/mediConnect.html

mediConnect 프로젝트 조회기능 수정, 게시글 전체조회기능 만들기

---

HTML/main/main.css
HTML/main/main.html
project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/AuthController.java
project/PSMC/src/main/java/com/javaclass/psmc/auth/model/dto/ProjectsDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/auth/model/dto/TheraProjectDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/static/assets/css/mainpage.css
project/PSMC/src/main/resources/templates/auth/login.html
project/untitled/.idea/gradle.xml

의사와 치료사 스케쥴 연동
오늘의 메뉴 연동
#67 
어떤 변경 사항이 있나요?

메인페이지 스케쥴 연동

---

HTML/main/main.css
HTML/main/main.html
project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/AuthController.java
project/PSMC/src/main/java/com/javaclass/psmc/auth/model/dto/MyPatientDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/common/model/method/MakePhoneNumber.java
project/PSMC/src/main/java/com/javaclass/psmc/common/model/method/MenuHandling.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/MyPageController.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/AllTheraDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/AssignToEmpDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/ConnectProjectDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/CreateToEmpDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/MItoProDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/ProfileDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/TheraToProDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/TodayMenuDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/TtoMIDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/dto/LoginUserDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/static/assets/css/mainpage.css
project/PSMC/src/main/resources/static/assets/js/schedule.js
project/PSMC/src/main/resources/templates/auth/login.html

메인페이지 식단표와 예약 crud 작업 마쳤습니다
#120 
어떤 변경 사항이 있나요?

main page 식단표 crud 작업

---

project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/AuthController.java
project/PSMC/src/main/java/com/javaclass/psmc/auth/model/dto/ProjectsDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/auth/model/dto/TheraProjectDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/MyPageController.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/AllMediDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/AllTheraDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/templates/auth/login.html

main page doctor 예약 완료

---

project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/AuthController.java
project/PSMC/src/main/java/com/javaclass/psmc/auth/model/dto/TheraProjectDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/TheraInfoDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/common/model/method/FindTimeCode.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/MyPageController.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/TheraJSONDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/TodayAllMediDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/TodayAllTheraDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/templates/auth/login.html

메인페이지 예약기능 d,t 모두 완료 (시간 제한또한 완료)
#120 
어떤 변경 사항이 있나요?

메인페이지 예약 기능 제한

---

project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/MyPageController.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/ScheduleController.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/templates/auth/login.html
project/PSMC/src/main/resources/templates/schedule/scheduler.html

시간과 관련된 예약 / 수정 / 삭제 모두 완료 했습니다
#120 #62 
어떤 변경 사항이 있나요?

메인페이지 와 스케쥴러 예약 및 수정 시간 제한 설정 완료

---

project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/controller/MediConnectController.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/dao/ProjectsMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/service/MediConnectService.java
project/PSMC/src/main/resources/mappers/ProjectMapper.xml
project/PSMC/src/main/resources/templates/doc/mediConnect.html

mediConnect delete 기능 중간 커밋

---

project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/controller/MediConnectController.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/controller/ProjectsController.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/dao/ProjectsMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/service/MediConnectService.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/service/ProjectsService.java
project/PSMC/src/main/resources/mappers/ProjectMapper.xml
project/PSMC/src/main/resources/templates/doc/mediConnect.html
project/PSMC/src/main/resources/templates/doc/projects.html

메디커넥트 삭제하기

---

HTML/main/main.css
HTML/main/main.html
project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/MainController.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/MyPageController.java
project/PSMC/src/main/resources/application.yml
project/PSMC/src/main/resources/static/assets/css/mainpage.css
project/PSMC/src/main/resources/static/assets/css/schedule.css
project/PSMC/src/main/resources/static/assets/js/schedule.js
project/PSMC/src/main/resources/templates/auth/login.html
project/PSMC/src/main/resources/templates/member/registerReq.html
project/PSMC/src/main/resources/templates/schedule/scheduler.html

modal update

---

project/PSMC/src/main/resources/static/assets/css/mainpage.css

mainpage 약간 또 수정 (폰트)

---

project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/AuthController.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/MyPageController.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/templates/auth/login.html

main page modal input 제한 조건 완수

---

project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/MyPageController.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/templates/auth/login.html

메인페이지 mediconnect theralink db column 제외 완료

---

change/change.css
change/change.html
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/ChangeController.java
project/PSMC/src/main/resources/static/assets/css/change.css
project/PSMC/src/main/resources/static/assets/css/edit.css
project/PSMC/src/main/resources/static/assets/css/mypage.css
project/PSMC/src/main/resources/static/assets/js/change.js
project/PSMC/src/main/resources/templates/mypage/change.html
project/PSMC/src/main/resources/templates/mypage/edit.html
project/PSMC/src/main/resources/templates/mypage/mypage.html

마이페이지 수정 + 비밀번호 변경 완성

---

HTML/staff/staff.css
HTML/staff/staff.html
project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/StaffController.java

[HTML/CSS] staff 페이지

---

HTML/TheraLink/firstPage.html
HTML/TheraLink/general.css
HTML/TheraLink/secondPage.html
HTML/TheraLink/thirdPage.html
HTML/header/header.css
HTML/header/header.html
project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/AuthController.java
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/templates/auth/login.html

theralink 시작

---

HTML/mediConnect/mediConnect.css
HTML/mediConnectDetail/mediConnectDetail copy.css
HTML/mediConnectDetail/mediConnectDetail copy.html
HTML/mediConnectDetail/mediConnectDetail.css
HTML/mediConnectDetail/mediConnectDetail.html
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/controller/ProjectsController.java

[html/css] mediConnectDetail 디자인 초기

---

.idea/workspace.xml
project/PSMC/src/main/resources/static/assets/css/header.css
project/PSMC/src/main/resources/static/assets/css/mainpage.css
project/PSMC/src/main/resources/static/assets/css/mypage.css
project/PSMC/src/main/resources/static/assets/css/nav.css
project/PSMC/src/main/resources/templates/auth/login.html
project/PSMC/src/main/resources/templates/common/header.html
project/PSMC/src/main/resources/templates/common/nav.html

navbar 수정 !!

---

project/PSMC/src/main/resources/static/assets/css/change.css
project/PSMC/src/main/resources/static/assets/css/edit.css
project/PSMC/src/main/resources/static/assets/css/mypage.css
project/PSMC/src/main/resources/static/assets/css/nav.css
project/PSMC/src/main/resources/templates/common/nav.html

nav랑 mypage 위치 약간 변경

---

HTML/mediConnectDetail/mediConnectDetail.css
HTML/mediConnectDetail/mediConnectDetail.html

[HTML/CSS] MediConnect Detail 디자인

---

HTML/mediConnectDetail/mediConnectDetail.css
HTML/mediConnectDetail/mediConnectDetail.html

[HTML/CSS] 테스트 최종

---

HTML/TheraLink/secondPage.html
project/PSMC/.gitignore
project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/TheraChatDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/MessageDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/TheraChatForBlogDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/TheraLinkForChatDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
project/PSMC/src/main/resources/application.yml
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/static/assets/css/secondPage.css
project/PSMC/src/main/resources/static/assets/js/secondPage.js
project/PSMC/src/main/resources/templates/theraLink/secondPage.html

[FEATURE]theraLink 이미 있는 채팅 끌어오기 끝

---

project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/MessageDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/static/assets/js/secondPage.js

[FEATURE]chatting 기능 업데이트

---

project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/controller/MediConnectController.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/dao/ProjectsMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/service/MediConnectService.java
project/PSMC/src/main/resources/mappers/ProjectMapper.xml
project/PSMC/src/main/resources/templates/doc/mediConnect.html
project/PSMC/src/main/resources/templates/doc/mediConnectDetail.html

[feature] mediConnectDetail 기능 만들기 시작

---

project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/static/assets/js/header.js
project/PSMC/src/main/resources/static/assets/js/secondPage.js
project/PSMC/src/main/resources/templates/common/nav.html

채팅기능 오류 수정
#164 
어떤 변경 사항이 있나요?

[BUGFIX]theralink 채팅 기능에 있던 오류 수정

---

HTML/TheraLink/chatting.css
HTML/TheraLink/secondPage.html
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/ChatDeleteDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/static/assets/css/chatting.css
project/PSMC/src/main/resources/static/assets/js/secondPage.js
project/PSMC/src/main/resources/templates/theraLink/secondPage.html

채팅 삭제 기능 추가했습니다
#169
어떤 변경 사항이 있나요?

[FEATURE] theralink 채팅 기능 삭제 완성

---

HTML/mediConnectDetail/mediConnectDetail.html
project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/TheraChatDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/controller/MediConnectController.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/controller/ProjectsController.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/dao/ProjectsMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/dto/ShowAllProjectsDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/dto/ShowMediConnectDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/service/MediConnectService.java
project/PSMC/src/main/resources/mappers/ProjectMapper.xml
project/PSMC/src/main/resources/static/assets/js/header.js
project/PSMC/src/main/resources/templates/medi/mediConnect.html
project/PSMC/src/main/resources/templates/medi/mediConnectDetail.html
project/PSMC/src/main/resources/templates/medi/projects.html

[feature]mediConnectDetail

---

HTML/TheraLink/image-uploader.min.js
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
project/PSMC/src/main/resources/application.yml
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/static/assets/js/image-uploader.min.js
project/PSMC/src/main/resources/templates/theraLink/secondPage.html

[FEATURE]THERALINK 사진 CONTROLLER에 보내기 성공

---

project/PSMC/src/main/resources/static/assets/css/change.css
project/PSMC/src/main/resources/static/assets/css/mediConnect.css
project/PSMC/src/main/resources/templates/medi/mediConnect.html

mediconnect css 완성

---

project/PSMC/src/main/java/com/javaclass/psmc/configuration/SecurityConfig.java
project/PSMC/src/main/java/com/javaclass/psmc/configuration/WebConfig.java
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/TheraLinkPhotoDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
project/PSMC/src/main/resources/application.yml
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/templates/theraLink/secondPage.html

theralink 사진 업로드 기능
어떤 변경 사항이 있나요?

[FEATURE]theralink 사진 업로드 기능

---

project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/TheraJSONDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/dto/TodayAllTheraDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/ChatDeleteDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/MessageDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/TheraChatForBlogDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/TheraLinkForChatDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/TheraLinkPhotoDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/TheraLinkWithMonthDTO.java
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/templates/theraLink/secondPage.html

[FEATURE] theralink 사진 업로드

---

project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/RecieveDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/TheraLinkForChatDTO.java
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/static/assets/js/secondPage.js
project/PSMC/src/main/resources/templates/theraLink/secondPage.html

[FEATURE]THERALINK blog 생성및 수정

---

project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/BlogDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/static/assets/js/secondPage.js
project/PSMC/src/main/resources/templates/common/nav.html
project/PSMC/src/main/resources/templates/theraLink/firstPage.html
project/PSMC/src/main/resources/templates/theraLink/secondPage.html

[BUGFIX] theralink 관련 버그 픽스

---

project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/controller/MediConnectController.java
project/PSMC/src/main/resources/templates/medi/mediConnectDetail.html

[Feature] mediConnect chatting 기능 1차 완성

---

project/PSMC/src/main/java/com/javaclass/psmc/mypage/controller/EditController.java
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/templates/theraLink/secondPage.html

[BUGFIX] theralink 사진관련 오류 수정했습니다

---

project/PSMC/src/main/java/com/javaclass/psmc/mypage/controller/EditController.java
project/PSMC/src/main/java/com/javaclass/psmc/mypage/model/dto/EditDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/mypage/model/service/EditService.java
project/PSMC/src/main/resources/mappers/EditMapper.xml
project/PSMC/src/main/resources/static/assets/js/edit.js
project/PSMC/src/main/resources/templates/mypage/edit.html

edit 굴러가는중..

---

project/PSMC/src/main/java/com/javaclass/psmc/common/model/dto/EmployeeDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/configuration/SecurityConfig.java
project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/MyPageController.java
project/PSMC/src/main/java/com/javaclass/psmc/mypage/controller/EditController.java
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/model/dto/TheraLinkForChatDTO.java
project/PSMC/src/main/resources/mappers/EditMapper.xml
project/PSMC/src/main/resources/mappers/ProjectMapper.xml
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/static/assets/js/secondPage.js
project/PSMC/src/main/resources/templates/mypage/edit.html

[DB] db 이름 수정

---

project/PSMC/src/main/resources/templates/mypage/edit.html

[feature] edit 완성

---

HTML/mediConnect/mediConnect.html
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/controller/MediConnectController.java
project/PSMC/src/main/resources/mappers/ProjectMapper.xml
project/PSMC/src/main/resources/static/assets/css/mediConnect.css
project/PSMC/src/main/resources/templates/medi/mediConnect.html

[feature] 메디커넥트 넣기 1차 완성

---

project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/controller/MediConnectController.java
project/PSMC/src/main/resources/mappers/ProjectMapper.xml
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/static/assets/js/mediConnect.js
project/PSMC/src/main/resources/templates/auth/login.html
project/PSMC/src/main/resources/templates/medi/mediConnect.html
project/PSMC/src/main/resources/templates/medi/mediConnectDetail.html
project/PSMC/src/main/resources/templates/medi/projects.html

[feature] 문제수정

---

project/PSMC/src/main/resources/templates/medi/mediConnectDetail.html

[feature] 채팅 비어있을 때 해결

---

project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/controller/ProjectsController.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/dao/ProjectsMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/dto/NewProjectShowDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/service/ProjectsService.java
project/PSMC/src/main/resources/mappers/ProjectMapper.xml

[bugfix] DTO 및 xml 수정

---

project/PSMC/src/main/java/com/javaclass/psmc/staff/controller/EmployeeController.java
project/PSMC/src/main/resources/templates/staff/list.html
project/PSMC/src/main/resources/templates/staff/search.html

[refactor]상대경로 수정

---

project/PSMC/src/main/resources/static/assets/css/secondPage.css
project/PSMC/src/main/resources/templates/theraLink/firstPage.html
project/PSMC/src/main/resources/templates/theraLink/secondPage.html

[HTML/CSS]theralink 컨텐츠가 없을때 빈공간 관련 이미지

---

project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/controller/MediConnectController.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/controller/ProjectsController.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/dao/ProjectsMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/dto/NewProjectShowDTO.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/model/service/MediConnectService.java
project/PSMC/src/main/resources/mappers/ProjectMapper.xml
project/PSMC/src/main/resources/templates/medi/mediConnectDetail.html
project/PSMC/src/main/resources/templates/medi/projects.html

[feature] 프로필 사진 띄우기

---

project/PSMC/src/main/java/com/javaclass/psmc/mainPage/model/controller/ScheduleController.java

[BUGFIX] SCHEULER 에서 상대경로 오류 수정

---

project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/controller/MediConnectController.java
project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/controller/ProjectsController.java
project/PSMC/src/main/resources/static/assets/css/mediConnect.css
project/PSMC/src/main/resources/static/assets/js/mediConnect.js
project/PSMC/src/main/resources/templates/medi/mediConnect.html
project/PSMC/src/main/resources/templates/medi/mediConnectDetail.html
project/PSMC/src/main/resources/templates/medi/projects.html

[CSS] mediConnect css 수정

---

project/PSMC/src/main/resources/templates/mypage/mypage.html

[html]mypage html 간단 수정

---

project/PSMC/src/main/java/com/javaclass/psmc/mediConnect/controller/MediConnectController.java
project/PSMC/src/main/resources/templates/medi/mediConnectDetail.html

[bugfix] mediConnect 상대/절대 경로 수정

---

project/PSMC/src/main/resources/mappers/ProjectMapper.xml

[bugfix] 검색링크 문제 해결

---

project/PSMC/src/main/resources/mappers/ProjectMapper.xml
project/PSMC/src/main/resources/templates/medi/mediConnectDetail.html

[bugfix]mediconnectbug fix

---

project/PSMC/src/main/java/com/javaclass/psmc/auth/controller/AuthController.java
project/PSMC/src/main/java/com/javaclass/psmc/theraLink/controller/TheraLinkController.java
project/PSMC/src/main/java/com/javaclass/psmc/user/controller/RegisterController.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/dao/UserMapper.java
project/PSMC/src/main/java/com/javaclass/psmc/user/model/service/UserService.java
project/PSMC/src/main/resources/mappers/UserMapper.xml
project/PSMC/src/main/resources/static/assets/css/registerReq.css
project/PSMC/src/main/resources/static/assets/js/mypage.js
project/PSMC/src/main/resources/static/assets/js/registerReq.js
project/PSMC/src/main/resources/templates/member/registerReq.html

[HTML/CSS] register css 변경
